### ISSUE TITLE
Error.inflateFailed when the acquired publication has unknown or no extension

### ISSUE THREAD

**Issue by xabierXercode** [readium/r2-lcp-swift#103] opened 2020-11-04 17:54 UTC
Hello when trying to open a book I have the following errors:

/OEBPS/01cap.html: other(ReadiumLCP.LCPDecryptor.Error.inflateFailed)
/OEBPS/04cap.html: other(ReadiumLCP.LCPDecryptor.Error.inflateFailed)
/OEBPS/02cap.html: other(ReadiumLCP.LCPDecryptor.Error.inflateFailed)
/OEBPS/03cap.html: other(ReadiumLCP.LCPDecryptor.Error.inflateFailed)

The license:

{"provider":"https:\/\/xeread.xebook.es","id":"45bb3de7-3228-4cac-a763-6bb0c8fa7aad","issued":"2020-11-05T12:06:45Z","encryption":{"profile":"http:\/\/readium.org\/lcp\/basic-profile","content_key":{"algorithm":"http:\/\/www.w3.org\/2001\/04\/xmlenc#aes256-cbc","encrypted_value":"9CY9HTOuV5P1JusL2LKntjAXzl9YTsWlehP6jrAmpt3YmBp5GUGk9M4Ndo8HfD6QKC1mKt+0HKA9zsKpa\/3Owg=="},"user_key":{"algorithm":"http:\/\/www.w3.org\/2001\/04\/xmlenc#sha256","text_hint":"Go to library","key_check":"Wa7PB07HI2f5IrHda6zv2HzWBOb+D0sI+1cDfDmMX2jdWLxo3PskzUMk7bgSjb442i+QnkrmGniChDERwuvtSQ=="}},"links":[{"rel":"status","href":"https:\/\/drm.xebook.es\/api\/licenses\/45bb3de7-3228-4cac-a763-6bb0c8fa7aad\/status","type":"application\/vnd.readium.license.status.v1.0+json"},{"rel":"hint","href":"https:\/\/drm.xebook.es\/static\/hint.html","type":"text\/html"},{"rel":"publication","href":"https:\/\/drm.xebook.es\/api\/publications\/dc2242f7-ec6f-11ea-bc9f-22000a538907\/contents","type":"application\/epub+zip","title":"dc2242f7-ec6f-11ea-bc9f-22000a538907","length":1549248,"hash":"9c7744611af601cb2ce3ef827590896f04c65d58afb5531e620f10d1e965c447"}],"user":{"id":"drm:uid:528-101-87c5e0df6fb948b4ad22eb7d0807737bbdcb62b1","email":"qGtYbM5tzJAOQv0ddllVPzRbMJHsDqa0pb5eFfTO9QLnfVNO6\/XqKw5DkxIYo05x","name":"K7G+tNgBoW7luDxWDXPJvvX2I9kPpHJ9lnrjGhSjmC3YfUcVCsUYy172z4sL6Z24","encrypted":["name","email"]},"rights":{"print":0,"copy":0,"start":"2020-11-05T12:06:44Z","end":"2020-11-12T22:59:00Z"},"signature":{"certificate":"MIIFpTCCA42gAwIBAgIBATANBgkqhkiG9w0BAQsFADBnMQswCQYDVQQGEwJGUjEOMAwGA1UEBxMFUGFyaXMxDzANBgNVBAoTBkVEUkxhYjESMBAGA1UECxMJTENQIFRlc3RzMSMwIQYDVQQDExpFRFJMYWIgUmVhZGl1bSBMQ1AgdGVzdCBDQTAeFw0xNjAzMjUwMzM3MDBaFw0yNjAzMjMwNzM3MDBaMIGQMQswCQYDVQQGEwJGUjEOMAwGA1UEBxMFUGFyaXMxDzANBgNVBAoTBkVEUkxhYjESMBAGA1UECxMJTENQIFRlc3RzMSIwIAYDVQQDExlUZXN0IHByb3ZpZGVyIGNlcnRpZmljYXRlMSgwJgYJKoZIhvcNAQkBFhlsYXVyZW50LmxlbWV1ckBlZHJsYWIub3JnMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAq\/gFXdvKb+EOzsEkHcoSOcPQmNzivzf+9NOJcxWi1\/BwuxqAAPv+4LKoLz89U1xx5TE1swL11BsEkIdVYrjl1RiYRa8YV4bb4xyMTm8lm39P16H1fG7Ep8yyoVuN6LT3WT2xHGp2jYU8I2nW78cyYApAWAuiMc3epeIOxC2mKgf1pGnaX9j5l\/Rx8hhxULqoHIHpR8e1eVRC7tgAz4Oy5qeLxGoL4S+GK\/11eRlDO37whAWaMRbPnJDqqi8Z0Beovf6jmdoUTJdcPZZ9kFdtPsWjPNNHDldPuJBtCd7lupc0K4pClJSqtJKyxs05Yeb1j7kbs\/i3grdlUcxz0zOaPN1YzrzOO7GLEWUnIe+LwVXAeUseHedOexITyDQXXCqMoQw\/BC6ApGzR0FynC6ojq98tStYGJAGbKBN\/9p20CvYf4\/hmPU3fFkImWguPIoeJT\/\/0rz+nSynykeEVtORRIcdyOnX2rL03xxBW7qlTlUXOfQk5oLIWXBW9Z2Q63MPWi8jQhSI0jC12iEqCT54xKRHNWKr04at9pJL85M0bDCbBH\/jJ+AIbVx02ewtXcWgWTgK9vgSPN5kRCwIGaV9PMS193KHfNpGqV45EKrfP8U2nvNDeyqLqAN5847ABSW7UmA5Kj\/x5uGxIWu9MUKjZlT0FpepswFvMMo1InLHANMcCAwEAAaMyMDAwDAYDVR0TAQH\/BAIwADALBgNVHQ8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggIBAEGAqzHsCbrfQwlWas3q66FG\/xbiOYQxpngA4CZWKQzJJDyOFgWEihW+H6NlSIH8076srpIZByjEGXZfOku4NH4DGNOj6jQ9mEfEwbrvCoEVHQf5YXladXpKqZgEB2FKeJVjC7yplelBtjBpSo23zhG\/o3\/Bj7zRySL6gUCewn7z\/DkxM6AshDE4HKQxjxp7stpESev+0VTL813WXvwzmucr94H1VPrasFyVzQHj4Ib+Id1OAmgfzst0vSZyX6bjAuiN9yrs7wze5cAYTaswWr7GAnAZ\/r1Z3PiDp50qaGRhHqJ+lRAhihpFP+ZjsYWRqnxZnDzJkJ6RZAHi2a3VN8x5WhOUMTf3JZcFVheDmA4SaEjAZAHU8zUxx1Fstjc8GJcjTwWxCsVM2aREBKXAYDhPTVLRKt6PyQxB0GxjDZZSvGI9uXn6S5wvjuE4T2TUwbJeGHqJr4FNpXVQ2XNww+sV2QSiAwrlORm8HNXqavj4rqz1PkUySXJ6b7zbjZoiACq4C7zb70tRYDyCfLTYtaTL3UK2Sa9ePSl0Fe6QfcqlGjalrqOo4GI6oqbAIkIXocHHksbLx0mIMSEWQOax+DqXhsl8tNGVwa5EiUSy83Sc0LyYXoWA35q8dugbkeNnY94rNG\/hYKeci1VHhyg4rqxEeVwfBx121JqQSs+hHGKt","value":"OC\/5kcChE+5ibx4TRY1IrZ7SQMyDCoMNeQVV8UBDaO+alB4zyxX5ysy3bQKnBw1Yhb48aaErl3\/46E6HAi1SBmH6IPHn0Yk\/ZA+IBsQrP8psynG35t+IrRCGbyzSfs\/yxCYYAGInEBf4qr1\/mTnAVroBx1ldu82uztp+Mk7OOFC1jfNvK1QI3aZkOn\/5UIZQtK+eJY1MVqKHoaIrytvFGYS5RqfaTHXpG90RZE+cpwBRObnE3NINzX4tw09FcKXIRjzcCllDbHpdcanrMwzY0JSCgr+ZEExeGVSAoWry\/d671ppW\/6XjozSz+RRdyKJ15CygKLx8CT5fWE+gAwTwErFxanaLhH3mlF4D3LN4Ub\/4ZFMGYTOnDNWnUeRk\/F87937ogw00RLms6TVlfUarngq0cAQLQYzxdrUyqW6IDhs2yshvP3+YrS7p4g2fLAK2gWy2NWzkqavtIwdMuTpl8Z2WOihhGiqj\/mfz9hmuwwTmT1Q8ORYo1XfnAeuJPW0MMjFUdTT+Bi5sa89TCGpLI+73PH8Th4oVTrrv5JSZY2rzurtomHVQ2u6dUdlxHaeMBBVAQTK6jlpYwnqjzRPT8sP4amQpQ7civzgzzbaY1gIAevhWaaxz46B0r4ikWtsGWzzpztcfnpryQTMSxBGxNm6fLlq4A8lWQ9Crd8o\/qXA=","algorithm":"http:\/\/www.w3.org\/2001\/04\/xmldsig-more#rsa-sha256"}}

The password:  demo-mobile@xebook.es

**Comment by mickael-menu** [comment] 2020-11-04 18:01
Most likely an issue with the encrypted file, take a look at this thread on Slack from someone who got the same error:

https://readium.slack.com/archives/C4APPBHUZ/p1601569906006500

**Comment by xabierXercode** [comment] 2020-11-05 14:14
I have had the same error, in the debugger, in the epub pages it shows the errror {"succes": false}

**Comment by mickael-menu** [comment] 2020-11-05 17:04
I can't test myself, it tells me that the passphrase is incorrect for this license, can you double-check the passphrase you gave us?

**Comment by xabierXercode** [comment] 2020-11-05 17:13
Sorry I must have made a mess between the license and the key I have updated the initial comment with the correct data

**Comment by mickael-menu** [comment] 2020-11-05 18:04
I can open the book from version 2.0.0-alpha.2. Could you send me the publication that you acquired on your device and are trying to open with the app, so I can check its content?

![simulator_screenshot_02520C40-58DB-4C7E-BB69-405C9BC157FB](https://user-images.githubusercontent.com/58686775/98278986-a4c89c00-1f99-11eb-8d86-b47b7e9674b7.png)

**Comment by xabierXercode** [comment] 2020-11-06 07:31
I don't keep the file, but I have already found the problem.

This occurs when you call the LCP license server and download the protected content. It downloads correctly but:

It fails if the downloaded file with the protected content epub or pdf has no extension.

It fails if the file downloaded with the content has a .zip extension instead of .epub or .lcpdf

Improvement suggestion: I think that the decryption libraries should use the type field of the license to determine the content type and not the file extension.

Thanks for your time

**Comment by mickael-menu** [comment] 2020-11-06 08:50
Okay thanks for reporting it, I'll take a look at this.

**Comment by mickael-menu** [comment] 2021-02-09 13:42
This should be fixed in https://github.com/readium/r2-lcp-swift/pull/97/files#diff-e43401ad1cf75df2636b4c173470680b06cf818db87d40b8c4516553b56623c5R180-R198 which is already merged in `develop`.

Please reopen if the issue is still around.

**Closed by mickael-menu** 2021-02-09 13:42 UTC
Labels: documentation needed
